### ISSUE TITLE
SNSにリンクを貼ったときのプレビュー機能

### ISSUE THREAD

**Issue by noss3885** [YNUCPC/cpc-hp#14]
Twitter等で投稿するときにバナーの画像や要約文が出るようになると見栄えがいいかなと思います。

htmlのheaderに情報を追加するとできるようです。

参考
https://ferret-plus.com/610

**Comment by mzsrkeen10** [comment]
https://github.com/YNUCPC/cpc-hp/blob/master/layouts/partials/head.html

このファイルの下部にFacebook用の設定があるのを見つけました。
なので、ここにtwitter用の設定を書き加えれば出来そうな気がします。
ただ、記事ごとに要約やバナーを変えられるかはよく分かりません（調べてみます）

**Comment by mzsrkeen10** [comment]
https://gohugo.io/templates/internal/#configure-open-graph

Hugoの機能としてサポートされてるっぽいですね

**Comment by noss3885** [comment]
ありがとうございます。
Templateをそのまま呼び出すか必要なところだけ写すみたいになりそうでしょうか?

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html

**Comment by mzsrkeen10** [comment]
一部だけ写すとメンテナンス性が下がりそうなので，templateをそのまま呼び出す方が望ましい気がします．

ところで，上手く動いてるかの確認がしづらいですね・・・
（masterで試しても良いとは思いますが）

**Comment by noss3885** [comment]
テストをローカルでやるのは難しそうなので実際にTemplateを入れてやってみるしかなさそうですかね。
やってみても大丈夫でしょうか?

**Comment by mzsrkeen10** [comment]
はい、大丈夫です

**Comment by mzsrkeen10** [comment]
今ある記事でtwitter cardを表示すると，こんな感じですね．

![Screenshot_2019-04-04_14-25-51](https://user-images.githubusercontent.com/22275681/55531512-980d0380-56e5-11e9-8122-de76da9c5f8b.png)

画像を表示するためには，記事のfront-matter（一番上の設定を書く所）で( images | feature | cover | thumbnail )に画像ファイル名を設定する必要があるみたいです．

記事にbannerとは別にimages等の設定をしても良いですが，
ホームページ内の記事のサムネイルと，twitter cardで使うサムネイルが別の設定になっているのも妙な気がするので，
"banner"っていう変数の名前を"thumbnail"とかに変えてしまっても良いかもしれません．
（後者の場合は何箇所かファイル書き換えることになりますが，それは僕の方でやれるので大丈夫です）

**Comment by noss3885** [comment]
なるほど。よろしければお願いします。

**Comment by mzsrkeen10** [comment]
記事のtwitter cardはこんな感じになりました．

![Screenshot_2019-04-04_17-10-10](https://user-images.githubusercontent.com/22275681/55539890-b6cac480-56fc-11e9-9a8e-785282249eb8.png)

画像を指定していないページに関して，デフォルトの画像としてロゴの画像を入れてみました．

![Screenshot_2019-04-04_17-10-56](https://user-images.githubusercontent.com/22275681/55539929-d06c0c00-56fc-11e9-9a7d-aeea877278c1.png)

（サイズが合ってませんが・・・）

**Comment by noss3885** [comment]
ありがとうございます。これで機能は完成できたと思うのでこのissueは閉じようと思います。
