### ISSUE TITLE
トップページに公式TwitterのTLを埋め込む

### ISSUE THREAD

**Issue by noss3885** [YNUCPC/cpc-hp#48]
TLの埋め込みはこちらからできそうです。
https://help.twitter.com/ja/using-twitter/embed-twitter-feed
トップページに配置するにはどこに追加すればいいでしょうか。

**Comment by mzsrkeen10** [comment]
トップページのソースファイルは`themes/universal/layouts/index.html`です．
トップページの見た目を変更する場合は，このファイルを直接編集するのではなく，
`layouts/`ディレクトリに`index.html`をコピーした上で，この`layouts/index.html`を編集すれば良いです．

**Comment by noss3885** [comment]
`layouts/recent_posts.html`をいじってTLを表示させてみました。
記事数を4から3に少なくして空いたスペースに配置しました。
![image](https://user-images.githubusercontent.com/28915482/69726796-9f958700-1164-11ea-8679-81a360777ad4.png)
