### ISSUE TITLE
記事の管理について

### ISSUE THREAD

**Issue by noss3885** [YNUCPC/cpc-hp#54]
現在は`content/blog`下に直接記事のMarkdownファイルを置いていますが、今後記事が増えるのを考えると管理が煩雑になりそうだと思っています。

年度かカテゴリーで分けてフォルダにまとめたら良いと思うのですがいかがですか。

(ただそうすると記事リンクを張り直さないといけなくなるのですが…)

**Comment by mzsrkeen10** [comment]
以前 Hugo でそれをやろうとして、記事の一覧が生成されなくなって詰まったような記憶があります（記憶違いかも）。

年度で分けられるなら年度で分けた方が良いと思うので、ちょっと試してみてもらって良いですか？

リンクの張り直しは、 [aliases](https://gohugo.io/content-management/urls/#aliases) を使えば不要だと思います

**Comment by noss3885** [comment]
ローカルで試してみた結果

- `content/blog/`内であれば適当なフォルダに入れても記事一覧に表示される。
- `content/blog/`内のどのフォルダにあってもファイルの名前が同じならばホームページ上のURLは変わらない
- Hugoのショートカットリンクがダメになる (おそらく相対パスでみているので)

が分かりました。フォルダで管理すること自体はよさそうでファイル名を変更しなければaliasesは使わなくても大丈夫そうですがコンテスト一覧の記事リンクは修正が必要ですね

**Comment by noss3885** [comment]
とりあえず移動させてみました。

**Comment by mzsrkeen10** [comment]
なるほど， URL が変わらないなら aliases は意味ないですね
ローカルでの動作に問題が無さそうならマージして良いと思います

**Comment by noss3885** [comment]
無事マージできたのでここは閉じます
