### ISSUE TITLE
Contestsの一覧をMarkdownの表tableに置き換える

### ISSUE THREAD

**Issue by noss3885** [YNUCPC/cpc-hp#58]
現状が見にくいと思うのでBootstrapのtableにしたらどうかと思ったのですが、いかがですか

https://getbootstrap.com/docs/4.4/content/tables/

![現状](https://user-images.githubusercontent.com/28915482/77986206-7cb4f280-7351-11ea-938d-e128d1a7d275.png)

**Comment by mzsrkeen10** [comment]
とりあえず、比較のために Markdown の表をそのまま使った場合の見た目も載せてもらえると助かります

**Comment by noss3885** [comment]
試しに変更してみましたが、

- markdown中にがっつりhtmlを書くのはしんどい
- cssがサイトのテーマで変更されているため私が期待した見た目にならなかった
    - 表内の文字が太字になる、外枠などをつけると横幅の見た目が悪いなど
- cssを変更しても結果が手元のサーバーでは反映されない？
    - これは私がこのサイトの仕組みをよく理解していないせいだと思います...

が分かりました。

Markdownの表を使ったほうが明らかに楽で見た目もよいのでこちらで表にしようと思います。

![平日の活動をBootstrapのtableでまとめた例](https://user-images.githubusercontent.com/28915482/78269475-9c603c80-7544-11ea-828e-8313b116ffc8.png)
平日の活動をBootstrapのtableでまとめた例 (striped)

![週末の活動をMarkdownの表でまとめた例](https://user-images.githubusercontent.com/28915482/78269399-7f2b6e00-7544-11ea-9fc3-6d272fe44037.png)
週末の活動をMarkdownの表でまとめた例
